spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aidiyet
    username: aidiyet
    password: aidiyetpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ay5C5A3Uu3D4t0aLbfXpCtyehNQeNqWlJzX5aEvEn0o=
  expirationMs: 3600000

